package com.commerce_pro_backend.finance.entity;

import com.commerce_pro_backend.finance.enums.InvoiceStatus;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.annotations.UuidGenerator;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Customer-facing invoice document — the formal financial record for AR.
 * Linked to an Order (optional) but exists as a separate financial document.
 * Invoice number is INV-YYYYMMDD-NNNNNN, generated by InvoiceNumberService.
 */
@Entity
@Table(name = "customer_invoices", indexes = {
    @Index(name = "idx_ci_number",   columnList = "invoice_number",  unique = true),
    @Index(name = "idx_ci_order",    columnList = "order_id"),
    @Index(name = "idx_ci_customer", columnList = "customer_id"),
    @Index(name = "idx_ci_status",   columnList = "status"),
    @Index(name = "idx_ci_due_date", columnList = "due_date"),
    @Index(name = "idx_ci_period",   columnList = "period_id"),
    @Index(name = "idx_ci_issued",   columnList = "issued_at")
})
@Data @Builder @NoArgsConstructor @AllArgsConstructor
public class CustomerInvoice {

    @Id @UuidGenerator
    @Column(updatable = false, nullable = false)
    private String id;

    @Column(name = "invoice_number", nullable = false, unique = true, length = 30)
    private String invoiceNumber;

    // ── Cross-module links (plain String FKs — no @ManyToOne across modules) ─
    @Column(name = "order_id", length = 36)
    private String orderId;

    @Column(name = "order_number", length = 30)
    private String orderNumber;

    @Column(name = "customer_id", length = 36)
    private String customerId;

    @Column(name = "customer_name", nullable = false, length = 200)
    private String customerName;

    @Column(name = "customer_email", nullable = false, length = 255)
    private String customerEmail;

    @Column(name = "customer_tax_id", length = 50)
    private String customerTaxId;

    @Column(name = "billing_address", columnDefinition = "TEXT")
    private String billingAddress;         // JSON snapshot at invoice time

    // ── Period ────────────────────────────────────────────────────────────────
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "period_id")
    private FinancialPeriod period;

    // ── Status & Dates ────────────────────────────────────────────────────────
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    @Builder.Default
    private InvoiceStatus status = InvoiceStatus.DRAFT;

    @Column(name = "issued_at")
    private LocalDateTime issuedAt;

    @Column(name = "due_date", nullable = false)
    private LocalDate dueDate;

    @Column(name = "paid_at")
    private LocalDateTime paidAt;

    @Column(name = "voided_at")
    private LocalDateTime voidedAt;

    @Column(name = "void_reason", length = 500)
    private String voidReason;

    // ── Financial Totals (precision=19, scale=4) ──────────────────────────────
    @Column(name = "subtotal", nullable = false, precision = 19, scale = 4)
    @Builder.Default private BigDecimal subtotal = BigDecimal.ZERO;

    @Column(name = "discount_amount", nullable = false, precision = 19, scale = 4)
    @Builder.Default private BigDecimal discountAmount = BigDecimal.ZERO;

    @Column(name = "tax_amount", nullable = false, precision = 19, scale = 4)
    @Builder.Default private BigDecimal taxAmount = BigDecimal.ZERO;

    @Column(name = "shipping_amount", nullable = false, precision = 19, scale = 4)
    @Builder.Default private BigDecimal shippingAmount = BigDecimal.ZERO;

    @Column(name = "total_amount", nullable = false, precision = 19, scale = 4)
    @Builder.Default private BigDecimal totalAmount = BigDecimal.ZERO;

    @Column(name = "paid_amount", nullable = false, precision = 19, scale = 4)
    @Builder.Default private BigDecimal paidAmount = BigDecimal.ZERO;

    @Column(name = "balance_due", nullable = false, precision = 19, scale = 4)
    @Builder.Default private BigDecimal balanceDue = BigDecimal.ZERO;

    @Column(name = "currency", nullable = false, length = 3)
    @Builder.Default private String currency = "USD";

    @Column(name = "exchange_rate", precision = 19, scale = 6)
    @Builder.Default private BigDecimal exchangeRate = BigDecimal.ONE;

    // ── Metadata ──────────────────────────────────────────────────────────────
    @Column(name = "notes", length = 2000)
    private String notes;

    @Column(name = "payment_terms", length = 100)
    private String paymentTerms;           // "Net 30", "Due on Receipt"

    @Column(name = "tax_jurisdiction_id", length = 36)
    private String taxJurisdictionId;

    // ── Audit ─────────────────────────────────────────────────────────────────
    @CreationTimestamp
    @Column(name = "created_at", updatable = false, nullable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @Column(name = "created_by", updatable = false, length = 36)
    private String createdBy;

    @Column(name = "updated_by", length = 36)
    private String updatedBy;

    // ── Relationships ─────────────────────────────────────────────────────────
    @OneToMany(mappedBy = "invoice", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    @Builder.Default
    private List<CustomerInvoiceItem> items = new ArrayList<>();

    // ── Business Methods ──────────────────────────────────────────────────────

    public boolean isOverdue() {
        return (status == InvoiceStatus.SENT || status == InvoiceStatus.PARTIALLY_PAID)
            && LocalDate.now().isAfter(dueDate);
    }

    public void recalculateTotals() {
        this.subtotal = items.stream()
            .map(CustomerInvoiceItem::getLineTotal)
            .reduce(BigDecimal.ZERO, BigDecimal::add);
        this.totalAmount = subtotal
            .subtract(discountAmount)
            .add(taxAmount)
            .add(shippingAmount);
        if (this.totalAmount.compareTo(BigDecimal.ZERO) < 0) this.totalAmount = BigDecimal.ZERO;
        this.balanceDue = totalAmount.subtract(paidAmount).max(BigDecimal.ZERO);
    }

    /**
     * AR aging bucket:
     * 0 = current/paid, 1 = 1-30d overdue, 2 = 31-60d, 3 = 61-90d, 4 = 90d+
     */
    public int computeAgingBucket() {
        if (status == InvoiceStatus.PAID || status == InvoiceStatus.VOID
                || status == InvoiceStatus.WRITTEN_OFF) return 0;
        if (dueDate == null) return 0;
        long daysOverdue = LocalDate.now().toEpochDay() - dueDate.toEpochDay();
        if (daysOverdue <= 0)  return 0;
        if (daysOverdue <= 30) return 1;
        if (daysOverdue <= 60) return 2;
        if (daysOverdue <= 90) return 3;
        return 4;
    }
}
