package com.commerce_pro_backend.finance.enums;
public enum JournalEntryType {
    ORDER_REVENUE, ORDER_REFUND, ORDER_TAX, ORDER_SHIPPING, COGS,
    EXPENSE, AP_PAYMENT, AR_RECEIPT, PAYMENT_FEE, CHARGEBACK,
    MANUAL_ADJUSTMENT, DEPRECIATION, EXCHANGE_GAIN_LOSS
}
