// AuditAction.java
package com.commerce_pro_backend.user_identity.enums;

public enum AuditAction {
    // User actions
    USER_CREATED, USER_UPDATED, USER_DELETED, USER_ACTIVATED, USER_DEACTIVATED,
    USER_LOCKED, USER_UNLOCKED, PASSWORD_CHANGED, PASSWORD_RESET, USER_IMPERSONATED,
    
    // Role actions
    ROLE_CREATED, ROLE_UPDATED, ROLE_DELETED, ROLE_ASSIGNED, ROLE_REVOKED,
    PERMISSION_GRANTED, PERMISSION_REVOKED, PERMISSION_CREATED, PERMISSION_UPDATED,
    PERMISSION_DELETED,
    
    // Security actions
    LOGIN_SUCCESS, LOGIN_FAILURE, LOGOUT, SESSION_TERMINATED,
    MFA_ENABLED, MFA_DISABLED, MFA_VERIFIED,
    
    // Configuration
    CONFIG_UPDATED, POLICY_CHANGED,
    
    // Audit
    AUDIT_VIEWED, REPORT_GENERATED, AUDIT_PURGED, AUDIT_EXPORTED,

    // Order Management ─────────────────────────────────────────────────
    ORDER_CREATED,
    ORDER_UPDATED,
    ORDER_CONFIRMED,
    ORDER_CANCELLED,
    ORDER_SHIPPED,
    ORDER_DELIVERED,
    ORDER_CLOSED,
    ORDER_HELD,
    ORDER_HOLD_RELEASED,
    ORDER_STATUS_CHANGED,
    ORDER_TRACKING_UPDATED,
    ORDER_BULK_ACTION,

    // Fulfillment & WMS ────────────────────────────────────────────────────────
    FULFILLMENT_PICKLIST_CREATED,
    FULFILLMENT_PICKLIST_ASSIGNED,
    FULFILLMENT_PICKLIST_STARTED,
    FULFILLMENT_PICKLIST_COMPLETED,
    FULFILLMENT_PICKLIST_CANCELLED,
    FULFILLMENT_SHIPMENT_CREATED,
    FULFILLMENT_SHIPMENT_UPDATED,
    FULFILLMENT_SHIPMENT_TRACKING_ADDED,
    FULFILLMENT_SHIPMENT_DELETED,
    FULFILLMENT_CARRIER_CREATED,
    FULFILLMENT_CARRIER_UPDATED,
    FULFILLMENT_CARRIER_DELETED,
    FULFILLMENT_RULE_CREATED,
    FULFILLMENT_RULE_UPDATED,
    FULFILLMENT_RULE_DELETED,

    // Customer Management
    CUSTOMER_CREATED, CUSTOMER_UPDATED, CUSTOMER_DELETED,
    CUSTOMER_STATUS_CHANGED, CUSTOMER_TIER_CHANGED,
    CUSTOMER_BLACKLISTED, CUSTOMER_UNBLACKLISTED,
    CUSTOMER_FRAUD_FLAGGED, CUSTOMER_FRAUD_RESOLVED,
    CUSTOMER_LOYALTY_ADJUSTED,
    CUSTOMER_GROUP_CREATED, CUSTOMER_GROUP_UPDATED, CUSTOMER_GROUP_DELETED,

    // Analytics & Reporting
    REPORT_RUN,
    REPORT_EXPORTED,
    SAVED_REPORT_CREATED,
    SAVED_REPORT_UPDATED,
    SAVED_REPORT_DELETED,
    SCHEDULED_REPORT_CREATED,
    SCHEDULED_REPORT_UPDATED,
    SCHEDULED_REPORT_DELETED,
    SCHEDULED_REPORT_TRIGGERED
}