// AuditAction.java
package com.commerce_pro_backend.user_identity.enums;

public enum AuditAction {
    // User actions
    USER_CREATED, USER_UPDATED, USER_DELETED, USER_ACTIVATED, USER_DEACTIVATED,
    USER_LOCKED, USER_UNLOCKED, PASSWORD_CHANGED, PASSWORD_RESET, USER_IMPERSONATED,
    
    // Role actions
    ROLE_CREATED, ROLE_UPDATED, ROLE_DELETED, ROLE_ASSIGNED, ROLE_REVOKED,
    PERMISSION_GRANTED, PERMISSION_REVOKED, PERMISSION_CREATED, PERMISSION_UPDATED,
    PERMISSION_DELETED,
    
    // Security actions
    LOGIN_SUCCESS, LOGIN_FAILURE, LOGOUT, SESSION_TERMINATED,
    MFA_ENABLED, MFA_DISABLED, MFA_VERIFIED,
    
    // Configuration
    CONFIG_UPDATED, POLICY_CHANGED,
    
    // Audit
    AUDIT_VIEWED, REPORT_GENERATED, AUDIT_PURGED, AUDIT_EXPORTED,

    // Order Management ─────────────────────────────────────────────────
    ORDER_CREATED,
    ORDER_UPDATED,
    ORDER_CONFIRMED,
    ORDER_CANCELLED,
    ORDER_SHIPPED,
    ORDER_DELIVERED,
    ORDER_CLOSED,
    ORDER_HELD,
    ORDER_HOLD_RELEASED,
    ORDER_STATUS_CHANGED,
    ORDER_TRACKING_UPDATED,
    ORDER_BULK_ACTION,

    // Fulfillment & WMS ────────────────────────────────────────────────────────
    FULFILLMENT_PICKLIST_CREATED,
    FULFILLMENT_PICKLIST_ASSIGNED,
    FULFILLMENT_PICKLIST_STARTED,
    FULFILLMENT_PICKLIST_COMPLETED,
    FULFILLMENT_PICKLIST_CANCELLED,
    FULFILLMENT_SHIPMENT_CREATED,
    FULFILLMENT_SHIPMENT_UPDATED,
    FULFILLMENT_SHIPMENT_TRACKING_ADDED,
    FULFILLMENT_SHIPMENT_DELETED,
    FULFILLMENT_CARRIER_CREATED,
    FULFILLMENT_CARRIER_UPDATED,
    FULFILLMENT_CARRIER_DELETED,
    FULFILLMENT_RULE_CREATED,
    FULFILLMENT_RULE_UPDATED,
    FULFILLMENT_RULE_DELETED,

    // Customer Management
    CUSTOMER_CREATED, CUSTOMER_UPDATED, CUSTOMER_DELETED,
    CUSTOMER_STATUS_CHANGED, CUSTOMER_TIER_CHANGED,
    CUSTOMER_BLACKLISTED, CUSTOMER_UNBLACKLISTED,
    CUSTOMER_FRAUD_FLAGGED, CUSTOMER_FRAUD_RESOLVED,
    CUSTOMER_LOYALTY_ADJUSTED,
    CUSTOMER_GROUP_CREATED, CUSTOMER_GROUP_UPDATED, CUSTOMER_GROUP_DELETED,

    // Analytics & Reporting
    REPORT_RUN,
    REPORT_EXPORTED,
    SAVED_REPORT_CREATED,
    SAVED_REPORT_UPDATED,
    SAVED_REPORT_DELETED,
    SCHEDULED_REPORT_CREATED,
    SCHEDULED_REPORT_UPDATED,
    SCHEDULED_REPORT_DELETED,
    SCHEDULED_REPORT_TRIGGERED,

    // Payment & Finance
    PAYMENT_CREATED,
    PAYMENT_CAPTURED,
    PAYMENT_VOIDED,
    PAYMENT_FAILED,
    PAYMENT_FLAGGED,
    PAYMENT_SETTLED,

    REFUND_REQUESTED,
    REFUND_APPROVED,
    REFUND_REJECTED,
    REFUND_PROCESSED,
    REFUND_FAILED,

    CHARGEBACK_RECEIVED,
    CHARGEBACK_EVIDENCE_SUBMITTED,
    CHARGEBACK_ACCEPTED,
    CHARGEBACK_WON,
    CHARGEBACK_LOST,

    RECONCILIATION_GENERATED,
    RECONCILIATION_CLOSED,

    PAYOUT_CREATED,
    PAYOUT_APPROVED,
    PAYOUT_INITIATED,
    PAYOUT_COMPLETED,
    PAYOUT_CANCELLED,
    PAYOUT_FAILED,

    PAYMENT_LINK_CREATED,
    PAYMENT_LINK_DEACTIVATED,
    PAYMENT_LINK_PAID,

    PAYMENT_METHOD_ADDED,
    PAYMENT_METHOD_REMOVED,

    GATEWAY_CONFIG_CREATED,
    GATEWAY_CONFIG_UPDATED,
    GATEWAY_SET_ACTIVE,

    // Finance Module
    FINANCE_INVOICE_CREATED, FINANCE_INVOICE_SENT, FINANCE_INVOICE_PAID,
    FINANCE_INVOICE_VOIDED, FINANCE_INVOICE_WRITTEN_OFF,
    FINANCE_VENDOR_CREATED, FINANCE_VENDOR_UPDATED, FINANCE_VENDOR_STATUS_CHANGED,
    FINANCE_VENDOR_INVOICE_CREATED, FINANCE_VENDOR_INVOICE_APPROVED,
    FINANCE_VENDOR_INVOICE_REJECTED, FINANCE_VENDOR_INVOICE_PAID,
    FINANCE_EXPENSE_CREATED, FINANCE_EXPENSE_APPROVED,
    FINANCE_EXPENSE_REJECTED, FINANCE_EXPENSE_PAID,
    FINANCE_TAX_RATE_CREATED, FINANCE_TAX_RATE_UPDATED, FINANCE_TAX_RATE_DEACTIVATED,
    FINANCE_TAX_REPORT_GENERATED, FINANCE_TAX_REPORT_FILED,
    FINANCE_JOURNAL_POSTED, FINANCE_JOURNAL_REVERSED,
    FINANCE_PERIOD_CREATED, FINANCE_PERIOD_CLOSED, FINANCE_PERIOD_LOCKED, FINANCE_PERIOD_REOPENED,
    FINANCE_BUDGET_CREATED, FINANCE_BUDGET_APPROVED,
    FINANCE_EXCHANGE_RATE_ADDED,

    // AI Features
    AI_FRAUD_ANALYSED,
    AI_CHURN_PREDICTED,
    AI_DEMAND_FORECASTED,
    AI_SENTIMENT_ANALYSED,
    AI_PRICING_RECOMMENDED,
    AI_DESCRIPTION_GENERATED,
    AI_SEO_OPTIMISED,
    AI_INVENTORY_OPTIMISED,
    AI_MARKETING_PERSONALISED,
    AI_RETURNS_ANALYSED,
    AI_SHIPPING_OPTIMISED,
    AI_VENDOR_ANALYSED,
    AI_BUDGET_ANOMALY_DETECTED,
    AI_CHATBOT_SESSION_STARTED,
    AI_NL_REPORT_QUERIED,
    AI_CONFIG_UPDATED
}