package com.commerce_pro_backend.ai.enums;

public enum AiFeatureType {
    FRAUD_DETECTION,
    DEMAND_FORECAST,
    CHURN_PREDICTION,
    NL_REPORT,
    SUPPORT_CHATBOT,
    PRODUCT_DESCRIPTION,
    SENTIMENT_ANALYSIS,
    PRICING_RECOMMENDATION,
    INVENTORY_OPTIMIZATION,
    BUDGET_ANOMALY,
    SEO_OPTIMIZER,
    MARKETING_PERSONALIZATION,
    RETURN_PATTERN_ANALYSIS,
    VENDOR_ANALYSIS,
    SHIPPING_OPTIMIZATION
}
