package com.commerce_pro_backend.payment.enums;
public enum ChargebackReason { FRAUDULENT, DUPLICATE, PRODUCT_NOT_RECEIVED, PRODUCT_UNACCEPTABLE, CREDIT_NOT_PROCESSED, GENERAL, SUBSCRIPTION_CANCELLED, UNRECOGNIZED }
