package com.commerce_pro_backend.payment.enums;
public enum RefundReason { CUSTOMER_REQUEST, DAMAGED_ITEM, WRONG_ITEM_SHIPPED, ITEM_NOT_RECEIVED, QUALITY_ISSUE, DUPLICATE_CHARGE, ORDER_CANCELLED, PRICE_ADJUSTMENT, FRAUD, OTHER }
