package com.commerce_pro_backend.analytics.service;

import com.commerce_pro_backend.analytics.enums.ReportType;
import org.springframework.stereotype.Service;

import java.util.EnumMap;
import java.util.List;
import java.util.Map;

/**
 * Central registry of professional report export templates.
 *
 * <p>Every {@link ReportType} maps to a {@link ReportTemplate} that carries
 * a human-readable title, a category group, and an ordered list of column
 * definitions.  The definitions drive both the column headers written to CSV /
 * JSON exports <em>and</em> the column widths / header styles produced in the
 * professional XLSX output generated by {@link ReportExportService}.
 *
 * <p>Adding support for a new report type requires only a single entry here;
 * no changes to the export service itself are needed.
 */
@Service
public class ReportTemplateRegistry {

    // ── Column type hints (used for Excel cell number-format selection) ────────

    public enum ColumnType { TEXT, INTEGER, CURRENCY, DECIMAL, PERCENTAGE, DATE, BOOLEAN }

    /**
     * Single column descriptor: display label, preferred Excel column width
     * (in Excel character-unit approximation, typically ≈ chars × 1.1), and
     * a semantic type hint for cell formatting.
     */
    public record ColumnDef(String header, int width, ColumnType type) {}

    /**
     * Full template for one report type.
     *
     * @param title    Report heading written into the first row of the Excel sheet.
     * @param category Grouping label (Sales, Inventory, Orders, …).
     * @param columns  Ordered column definitions.
     */
    public record ReportTemplate(String title, String category, List<ColumnDef> columns) {}

    private final Map<ReportType, ReportTemplate> registry = new EnumMap<>(ReportType.class);

    public ReportTemplateRegistry() {
        buildRegistry();
    }

    /** Returns the template registered for the given report type, or a generic fallback. */
    public ReportTemplate getTemplate(ReportType type) {
        return registry.getOrDefault(type, defaultTemplate(type));
    }

    // ── Shared column-list constants ──────────────────────────────────────────

    /** Dimension-based sales breakdown (by date / product / category / channel). */
    private static final List<ColumnDef> SALES_COLUMNS = List.of(
        new ColumnDef("Period / Dimension",      28, ColumnType.TEXT),
        new ColumnDef("Revenue",                 16, ColumnType.CURRENCY),
        new ColumnDef("Discount",                14, ColumnType.CURRENCY),
        new ColumnDef("Tax",                     14, ColumnType.CURRENCY),
        new ColumnDef("Shipping",                14, ColumnType.CURRENCY),
        new ColumnDef("Refunded",                14, ColumnType.CURRENCY),
        new ColumnDef("Orders",                  12, ColumnType.INTEGER),
        new ColumnDef("Units Sold",              12, ColumnType.INTEGER),
        new ColumnDef("Avg Order Value",         16, ColumnType.CURRENCY),
        new ColumnDef("Share %",                 10, ColumnType.PERCENTAGE)
    );

    private static final List<ColumnDef> INVENTORY_STOCK_COLUMNS = List.of(
        new ColumnDef("Product Name",            32, ColumnType.TEXT),
        new ColumnDef("SKU",                     16, ColumnType.TEXT),
        new ColumnDef("Category",                20, ColumnType.TEXT),
        new ColumnDef("Warehouse",               20, ColumnType.TEXT),
        new ColumnDef("Qty On Hand",             14, ColumnType.INTEGER),
        new ColumnDef("Reserved",                12, ColumnType.INTEGER),
        new ColumnDef("Available",               12, ColumnType.INTEGER),
        new ColumnDef("Unit Cost",               14, ColumnType.CURRENCY),
        new ColumnDef("Total Value",             16, ColumnType.CURRENCY),
        new ColumnDef("Stock Status",            16, ColumnType.TEXT),
        new ColumnDef("Bin Location",            16, ColumnType.TEXT)
    );

    private static final List<ColumnDef> INVENTORY_MOVEMENT_COLUMNS = List.of(
        new ColumnDef("Movement ID",             28, ColumnType.TEXT),
        new ColumnDef("Product Name",            32, ColumnType.TEXT),
        new ColumnDef("SKU",                     16, ColumnType.TEXT),
        new ColumnDef("Warehouse",               20, ColumnType.TEXT),
        new ColumnDef("Movement Type",           18, ColumnType.TEXT),
        new ColumnDef("Quantity",                12, ColumnType.INTEGER),
        new ColumnDef("Previous Qty",            14, ColumnType.INTEGER),
        new ColumnDef("New Qty",                 12, ColumnType.INTEGER),
        new ColumnDef("Reason",                  24, ColumnType.TEXT),
        new ColumnDef("Reference",               20, ColumnType.TEXT),
        new ColumnDef("Date",                    22, ColumnType.DATE),
        new ColumnDef("Created By",              22, ColumnType.TEXT)
    );

    private static final List<ColumnDef> INVENTORY_AGEING_COLUMNS = List.of(
        new ColumnDef("Product Name",            32, ColumnType.TEXT),
        new ColumnDef("SKU",                     16, ColumnType.TEXT),
        new ColumnDef("Warehouse",               20, ColumnType.TEXT),
        new ColumnDef("Qty On Hand",             14, ColumnType.INTEGER),
        new ColumnDef("Total Value",             16, ColumnType.CURRENCY),
        new ColumnDef("Days Since Last Move",    22, ColumnType.INTEGER),
        new ColumnDef("Ageing Bucket",           16, ColumnType.TEXT),
        new ColumnDef("Last Movement Date",      22, ColumnType.DATE)
    );

    private static final List<ColumnDef> ORDER_COLUMNS = List.of(
        new ColumnDef("Order Number",            18, ColumnType.TEXT),
        new ColumnDef("Customer Name",           26, ColumnType.TEXT),
        new ColumnDef("Email",                   30, ColumnType.TEXT),
        new ColumnDef("Order Status",            18, ColumnType.TEXT),
        new ColumnDef("Fulfillment Status",      20, ColumnType.TEXT),
        new ColumnDef("Payment Status",          18, ColumnType.TEXT),
        new ColumnDef("Source / Channel",        18, ColumnType.TEXT),
        new ColumnDef("Total Amount",            16, ColumnType.CURRENCY),
        new ColumnDef("Item Count",              12, ColumnType.INTEGER),
        new ColumnDef("Created At",              22, ColumnType.DATE),
        new ColumnDef("Shipped At",              22, ColumnType.DATE),
        new ColumnDef("Delivered At",            22, ColumnType.DATE),
        new ColumnDef("Cancellation Reason",     26, ColumnType.TEXT),
        new ColumnDef("Carrier",                 16, ColumnType.TEXT),
        new ColumnDef("Tracking Number",         22, ColumnType.TEXT)
    );

    private static final List<ColumnDef> CUSTOMER_COLUMNS = List.of(
        new ColumnDef("Customer ID",             28, ColumnType.TEXT),
        new ColumnDef("Full Name",               26, ColumnType.TEXT),
        new ColumnDef("Email Address",           30, ColumnType.TEXT),
        new ColumnDef("Tier",                    14, ColumnType.TEXT),
        new ColumnDef("Status",                  14, ColumnType.TEXT),
        new ColumnDef("Total Orders",            14, ColumnType.INTEGER),
        new ColumnDef("Lifetime Spend",          18, ColumnType.CURRENCY),
        new ColumnDef("Avg Order Value",         18, ColumnType.CURRENCY),
        new ColumnDef("First Order Date",        20, ColumnType.DATE),
        new ColumnDef("Last Order Date",         20, ColumnType.DATE),
        new ColumnDef("Days Since Last Order",   22, ColumnType.INTEGER),
        new ColumnDef("Loyalty Points",          16, ColumnType.INTEGER),
        new ColumnDef("Acquisition Source",      22, ColumnType.TEXT),
        new ColumnDef("Segment",                 18, ColumnType.TEXT)
    );

    private static final List<ColumnDef> FINANCIAL_COLUMNS = List.of(
        new ColumnDef("Period",                  18, ColumnType.DATE),
        new ColumnDef("Gross Revenue",           18, ColumnType.CURRENCY),
        new ColumnDef("Net Revenue",             18, ColumnType.CURRENCY),
        new ColumnDef("COGS",                    16, ColumnType.CURRENCY),
        new ColumnDef("Gross Profit",            18, ColumnType.CURRENCY),
        new ColumnDef("Gross Margin %",          16, ColumnType.PERCENTAGE),
        new ColumnDef("Tax Collected",           18, ColumnType.CURRENCY),
        new ColumnDef("Refunds",                 16, ColumnType.CURRENCY)
    );

    private static final List<ColumnDef> SHIPPING_COLUMNS = List.of(
        new ColumnDef("Shipment Number",         22, ColumnType.TEXT),
        new ColumnDef("Order Number",            18, ColumnType.TEXT),
        new ColumnDef("Carrier",                 18, ColumnType.TEXT),
        new ColumnDef("Tracking Number",         24, ColumnType.TEXT),
        new ColumnDef("Status",                  20, ColumnType.TEXT),
        new ColumnDef("Shipped At",              22, ColumnType.DATE),
        new ColumnDef("Est. Delivery Date",      22, ColumnType.DATE),
        new ColumnDef("Actual Delivery Date",    22, ColumnType.DATE),
        new ColumnDef("Delivery Days",           16, ColumnType.INTEGER),
        new ColumnDef("On Time",                 12, ColumnType.BOOLEAN),
        new ColumnDef("Shipping Cost",           16, ColumnType.CURRENCY),
        new ColumnDef("Recipient City",          20, ColumnType.TEXT),
        new ColumnDef("Recipient Country",       20, ColumnType.TEXT)
    );

    private static final List<ColumnDef> RETURN_COLUMNS = List.of(
        new ColumnDef("Order Number",            18, ColumnType.TEXT),
        new ColumnDef("Customer Name",           26, ColumnType.TEXT),
        new ColumnDef("Product Name",            32, ColumnType.TEXT),
        new ColumnDef("SKU",                     16, ColumnType.TEXT),
        new ColumnDef("Returned Qty",            14, ColumnType.INTEGER),
        new ColumnDef("Refunded Amount",         18, ColumnType.CURRENCY),
        new ColumnDef("Return Reason",           24, ColumnType.TEXT),
        new ColumnDef("Order Status",            18, ColumnType.TEXT),
        new ColumnDef("Return Date",             22, ColumnType.DATE)
    );

    // ── Registry builder ──────────────────────────────────────────────────────

    private void buildRegistry() {
        // Sales
        registry.put(ReportType.SALES_OVERVIEW,
            new ReportTemplate("Sales Overview Report",          "Sales",     SALES_COLUMNS));
        registry.put(ReportType.SALES_BY_DATE,
            new ReportTemplate("Sales by Date Report",           "Sales",     SALES_COLUMNS));
        registry.put(ReportType.SALES_BY_PRODUCT,
            new ReportTemplate("Sales by Product Report",        "Sales",     SALES_COLUMNS));
        registry.put(ReportType.SALES_BY_CATEGORY,
            new ReportTemplate("Sales by Category Report",       "Sales",     SALES_COLUMNS));
        registry.put(ReportType.SALES_BY_CHANNEL,
            new ReportTemplate("Sales by Channel Report",        "Sales",     SALES_COLUMNS));

        // Inventory
        registry.put(ReportType.INVENTORY_STOCK_VALUE,
            new ReportTemplate("Inventory Stock Value Report",   "Inventory", INVENTORY_STOCK_COLUMNS));
        registry.put(ReportType.INVENTORY_MOVEMENT,
            new ReportTemplate("Inventory Movement Report",      "Inventory", INVENTORY_MOVEMENT_COLUMNS));
        registry.put(ReportType.INVENTORY_AGEING,
            new ReportTemplate("Inventory Ageing Report",        "Inventory", INVENTORY_AGEING_COLUMNS));

        // Orders
        registry.put(ReportType.ORDER_SUMMARY,
            new ReportTemplate("Order Summary Report",           "Orders",    ORDER_COLUMNS));
        registry.put(ReportType.ORDER_FULFILLMENT_RATE,
            new ReportTemplate("Order Fulfillment Rate Report",  "Orders",    ORDER_COLUMNS));
        registry.put(ReportType.ORDER_CANCELLATION_RATE,
            new ReportTemplate("Order Cancellation Rate Report", "Orders",    ORDER_COLUMNS));

        // Customers
        registry.put(ReportType.CUSTOMER_LTV,
            new ReportTemplate("Customer Lifetime Value Report", "Customers", CUSTOMER_COLUMNS));
        registry.put(ReportType.CUSTOMER_COHORT,
            new ReportTemplate("Customer Cohort Analysis",       "Customers", CUSTOMER_COLUMNS));
        registry.put(ReportType.CUSTOMER_CHURN,
            new ReportTemplate("Customer Churn Risk Report",     "Customers", CUSTOMER_COLUMNS));
        registry.put(ReportType.CUSTOMER_ACQUISITION,
            new ReportTemplate("Customer Acquisition Report",    "Customers", CUSTOMER_COLUMNS));

        // Financial
        registry.put(ReportType.FINANCIAL_REVENUE,
            new ReportTemplate("Financial Revenue Report",       "Financial", FINANCIAL_COLUMNS));
        registry.put(ReportType.FINANCIAL_MARGIN,
            new ReportTemplate("Margin Analysis Report",         "Financial", FINANCIAL_COLUMNS));
        registry.put(ReportType.FINANCIAL_TAX_SUMMARY,
            new ReportTemplate("Tax Summary Report",             "Financial", FINANCIAL_COLUMNS));

        // Shipping
        registry.put(ReportType.SHIPPING_ON_TIME_DELIVERY,
            new ReportTemplate("Shipping Delivery Report",       "Shipping",  SHIPPING_COLUMNS));
        registry.put(ReportType.SHIPPING_CARRIER_PERFORMANCE,
            new ReportTemplate("Carrier Performance Report",     "Shipping",  SHIPPING_COLUMNS));

        // Returns
        registry.put(ReportType.RETURN_RATE,
            new ReportTemplate("Return Rate Analysis Report",    "Returns",   RETURN_COLUMNS));
        registry.put(ReportType.RETURN_REASON_ANALYSIS,
            new ReportTemplate("Return Reason Analysis Report",  "Returns",   RETURN_COLUMNS));

        // Custom
        registry.put(ReportType.CUSTOM,
            new ReportTemplate("Custom Report",                  "Custom",    SALES_COLUMNS));
    }

    private ReportTemplate defaultTemplate(ReportType type) {
        return new ReportTemplate(
            type.name().replace("_", " ") + " Report",
            "Reports",
            SALES_COLUMNS
        );
    }
}
